version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: always
    ports:
      - 27017:27017"
    volumes:
      - mongodb_data_container:data/db
    depends_on:
      - app

  app:
    build:
      context: ./app
    container_name: app-server
    environment:
      - DATABASE_URL=mongodb://mongo:27017/app_db
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5000:5000"

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: reem
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
